2021-11-01 20:53:53,845 INFO    MainThread:11281 [wandb_setup.py:_flush():71] setting env: {}
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_init.py:_log_setup():357] Logging user logs to /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205353-3l8mhoo7/logs/debug.log
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_init.py:_log_setup():358] Logging internal logs to /work/lilu/HRSEPP/hrsepp/IO/wandb/run-20211101_205353-3l8mhoo7/logs/debug-internal.log
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_init.py:init():390] calling init triggers
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.008132, 'n_filters_factor': 1.111, 'filter_size': 3, 'batch_size': 2, 'epochs': 50}
2021-11-01 20:53:53,846 INFO    MainThread:11281 [wandb_init.py:init():435] starting backend
2021-11-01 20:53:53,847 INFO    MainThread:11281 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-11-01 20:53:53,876 INFO    MainThread:11281 [backend.py:ensure_launched():199] starting backend process...
2021-11-01 20:53:53,894 INFO    MainThread:11281 [backend.py:ensure_launched():205] started backend process with pid: 11329
2021-11-01 20:53:53,896 INFO    MainThread:11281 [wandb_init.py:init():444] backend started and connected
2021-11-01 20:53:53,897 INFO    MainThread:11281 [wandb_init.py:init():503] updated telemetry
2021-11-01 20:53:53,931 INFO    MainThread:11281 [wandb_init.py:init():533] communicating current version
2021-11-01 20:53:54,908 INFO    MainThread:11281 [wandb_init.py:init():538] got version response 
2021-11-01 20:53:54,908 INFO    MainThread:11281 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-01 20:53:55,261 INFO    MainThread:11281 [wandb_init.py:init():576] starting run threads in backend
2021-11-01 20:53:55,367 WARNING MainThread:11281 [wandb_init.py:init():891] interrupted
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 870, in init
    run = wi.init()
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 581, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 216, in communicate_run_start
    result = self._communicate_run_start(run_start)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 446, in _communicate_run_start
    result = self._communicate(rec)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/root/anaconda3/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 32, in get
    is_set = self._object_ready.wait(timeout)
  File "/root/anaconda3/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/root/anaconda3/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
